name: âœ… check
on: push
jobs:
  lint:
    name: ğŸ§¹ lint
    runs-on: macos-latest
    steps:
      - name: â¬‡ï¸ Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: âš™ï¸ Install swiftlint
        run: |
          brew install swiftlint
        env:
          HOMEBREW_NO_INSTALL_CLEANUP: 1
      - name: ğŸ§¹ Code Lint
        run: |
          if [ ! -f ".swiftlint.yml" ]; then
            curl -L https://raw.githubusercontent.com/4d-for-ios/check-workflow/master/form/quality/.swiftlint.yml --output .swiftlint.yml
          fi
          swiftlint --strict
      - name: âš™ï¸ Install iblinter
        run: |
          brew install IBDecodable/homebrew-tap/iblinter
        env:
          HOMEBREW_NO_INSTALL_CLEANUP: 1
      - name: ğŸ§¹ Storyboard Lint
        run: |
          if [ ! -f ".iblinter.yml" ]; then
            curl -L https://raw.githubusercontent.com/4d-for-ios/check-workflow/master/form/quality/.iblinter.yml --output .iblinter.yml
          fi
          iblinter lint
      - name: âš™ï¸ Install jsonlint
        run: |
          brew install jsonlint | tee
      - name: ğŸ§¹ Manifest Lint
        run: |
          cat manifest.json | jsonlint
  build:
    name: ğŸ— build
    runs-on: macos-latest
    env:
      RELEASE_REPO: "https://raw.githubusercontent.com/4d-for-ios/check-workflow/master"
    steps:
      - name: â¬‡ï¸ Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: ğŸ‘· Swift build
        run: |
          curl -fsSL $RELEASE_REPO/form/scripts/swift_build.sh | bash -s
